on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3.1.3
      - name: Pip Installer
        uses: BSFishy/pip-action@v1
        with:
          requirements: requirements.txt
      - name: npm installer
        uses: bahmutov/npm-install@v1
      - name: npm install
        run: npm install -g uglify-js
      - run: make github
