on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3.1.3
      - name: Pip Installer
        uses: BSFishy/pip-action@v1
        with:
          requirements: requirements.txt
      - name: npm setup
        uses: ng-easy/npm-setup@v1
      - name: install uglify-js
        run: npm install -g uglify-js
      - run: make github
